services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: API_ID
        value: "26571790"
      - key: API_HASH
        value: "85cf07a16f40cceb2cd7735600d59afc"
      - key: BOT_TOKEN
        value: "8012666118:AAG_5omiOeLn9q4Fd1tcUx3IbvDEK8VJf_8"
      - key: SESSION_STRING
        value: "BAGVdA4AnXs2uWT90zZza6TjbVAvRin8-BBDOfbyVppeZixwcqQdBF7gnnyJCJSaLieJvjWofwui0Rv365XOyR9HBzDVCMRXOFnh78P1AIn6xPenZZd9bD-dh0lqNDxMuFyrK1Vt7bgtl3gCVbpAjpZIALRrvtBzPfgzdA87dIFdyTV8pRCNK5nloeuJJJu1iuVKQkmo1IVMbhqfjab-UaeFesm71c0mp-4ZmqcgQmqLTLfJKoM5J-SmJx7tb9LlwvfX8UShrQ_iuodo9g4A66wP-4k8_XO04HBDcbYjLuhxuGQTiIat2HhnGTQ7mlNd4Su1CSz_bmZkitY1v7ulqhTlVSpCLwAAAAG13UY2AA"
